name: Spirits
version: ${project.version}
main: me.numin.spirits.Spirits
api-version: 1.13
depend: [ProjectKorra]
authors: [Numin]
description: Enables your players to be Spirits.

permissions:
  bending.water:
    default: false
    description: Grants access to all Water abilities.
    children:
      bending.ability.corrupt: true
      bending.ability.purify: true
  bending.spirit:
    default: true
    description: Grants access to all Spirit abilities.
    children:
      bending.ability.agility: true
      bending.ability.phase: true
      bending.ability.possess: true
      bending.ability.vanish: true
  bending.lightspirit:
    default: true
    description: Grants access to all LightSpirit abilities.
    children:
      bending.ability.alleviate: true
      bending.ability.orb: true
      bending.ability.rejuvenate: true
      bending.ability.shelter: true
  bending.darkspirit:
    default: true
    description: Grants access to all DarkSpirit abilities.
    children:
      bending.ability.infest: true
      bending.ability.intoxicate: true
      bending.ability.shackle: true
      bending.ability.strike: true